### PR TITLE
Add .gitignore, fix build on `master`

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes incompatibilities introduced in https://github.com/godotengine/godot/pull/64757, https://github.com/godotengine/godot/pull/65039, https://github.com/godotengine/godot/pull/65241, https://github.com/godotengine/godot/pull/65361

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+*.so
+# Binutils tmp linker output of the form "stXXXXXX" where "X" is alphanumeric
+st[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]
+
+# Python generated
+__pycache__/
+*.pyc
+
+# Temporary files.
+*.tmp
```
Comment (nathanfranke) [inline .gitignore:21]: Tentative change, copied a few sections from godotengine/godot, and added .tmp on the bottom, since that was the only other file being generated on my end.

**Comment by fire** [comment]
Do you want to merge this in now or after restore cicd?

**Comment by nathanfranke** [comment]
Before cicd would be better, that way the checks will pass as long as configuration is correct (and no additional incompatibilities)

**Comment by fire** [comment]
Can you write up how you generated this? It's not only useful for me to test the change but also as an introduction guide.

**Review by aaronfranke — APPROVED** [review]

**Comment by nathanfranke** [comment]
Didn't generate anything, all these changes are manual (gitignore is copied though)

**Comment by fire** [comment]
I checked the latest master. 

It's broken 

```
[ 73%] /home/elee/Documents/chibifire/groups-engine-workspace/godot-modules-groups/visual_script/editor/visual_script_editor.cpp:4922:93: error: no member named 'CMD_OR_CTRL' in 'KeyModifierMask'
        ED_SHORTCUT("visual_script_editor/find_node_type", TTR("Find Node Type"), KeyModifierMask::CMD_OR_CTRL + Key::F);
                                                                                  ~~~~~~~~~~~~~~~~~^
/home/elee/Documents/chibifire/groups-engine-workspace/godot-modules-groups/visual_script/editor/visual_script_editor.cpp:4923:93: error: no member named 'CMD_OR_CTRL' in 'KeyModifierMask'
        ED_SHORTCUT("visual_script_editor/create_function", TTR("Make Function"), KeyModifierMask::CMD_OR_CTRL + Key::G);
                                                                                  ~~~~~~~~~~~~~~~~~^
/home/elee/Documents/chibifire/groups-engine-workspace/godot-modules-groups/visual_script/editor/visual_script_editor.cpp:4924:91: error: no member named 'CMD_OR_CTRL' in 'KeyModifierMask'
        ED_SHORTCUT("visual_script_editor/refresh_nodes", TTR("Refresh Graph"), KeyModifierMask::CMD_OR_CTRL + Key::R);
                                                                                ~~~~~~~~~~~~~~~~~^
/home/elee/Documents/chibifire/groups-engine-workspace/godot-modules-groups/visual_script/editor/visual_script_editor.cpp:4925:87: error: no member named 'CMD_OR_CTRL' in 'KeyModifierMask'
        ED_SHORTCUT("visual_script_editor/edit_member", TTR("Edit Member"), KeyModifierMask::CMD_OR_CTRL + Key::E);
                                                                            ~~~~~~~~~~~~~~~~~^
4 errors generated.```

**Comment by nathanfranke** [comment]
Pull godotengine/godot, CMD_OR_CTRL was implemented in https://github.com/godotengine/godot/pull/65241 14 hours ago

**Comment by fire** [comment]
Looks good to me.
