### ISSUE TITLE
Scons error 2 when compiling

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-visual-script#78]
### Godot version

latest

### System information

Windows 10

### Issue description

Hello, I get the error 2 when compiling the latest godot source version with the visual script module. Here's the error in the cmd :

[Initial build] Compiling thirdparty\libwebp\src\dsp\rescaler_sse2.c ...
[Initial build] scons: *** [modules\visual_script\register_types.windows.editor.x86_64.obj] Error 2
Compiling thirdparty\libwebp\src\dsp\ssim.c ...
modules\visual_script\editor\visual_script_property_selector.cpp(43): fatal error C1083: Cannot open include file: 'editor/editor_scale.h': No such file or directory
rescaler_sse2.c
ssim.c
scons: *** [modules\visual_script\editor\visual_script_property_selector.windows.editor.x86_64.obj] Error 2
modules\visual_script\editor\visual_script_editor.cpp(45): fatal error C1083: Cannot open include file: 'editor/editor_scale.h': No such file or directory
scons: *** [modules\visual_script\editor\visual_script_editor.windows.editor.x86_64.obj] Error 2
scons: building terminated because of errors.
[Time elapsed: 00:01:38.589]

### Steps to reproduce

scons platform=windows

**Comment by Zylann** [comment]
The file moved recently in Godot's master branch <https://github.com/Zylann/godot_voxel/blob/71bf9a92c793adb74155b134232df8b22371b08f/util/godot/editor_scale.h#L11>

And a few other things <https://github.com/Zylann/godot_voxel/blob/71bf9a92c793adb74155b134232df8b22371b08f/util/godot/classes/graph_edit.cpp#L28>

**Comment by ghost** [comment]
> The file moved recently in Godot's master branch https://github.com/Zylann/godot_voxel/blob/71bf9a92c793adb74155b134232df8b22371b08f/util/godot/editor_scale.h#L11
> 
> And a few other things https://github.com/Zylann/godot_voxel/blob/71bf9a92c793adb74155b134232df8b22371b08f/util/godot/classes/graph_edit.cpp#L28

So what am I supposed to do ? (i'm new to this kind of stuff)

**Comment by Zylann** [comment]
I don't know the visualscript module, I just figured I would tell what the issue is for devs because I had the same problem.

There are places in the module with `#include <editor/editor_scale.h>`, but the path has changed, so to compile with Godot 4.3 they need to be replaced with `#include <editor/themes/editor_scale.h>`.
But if this module needs to keep working in older versions of Godot, it has to do what I did in the code I linked.

**Comment by ghost** [comment]
Ok thanks !

**Comment by ghost** [comment]
This is a never ending rabbit hole, I get other errors after the "fix" : 
modules\visual_script\register_types.cpp(51): error C2259: 'VisualScriptLanguage': cannot instantiate abstract class
D:\Godot Visual Scripting\godot\modules\visual_script\visual_script.h(542): note: see declaration of 'VisualScriptLanguage'
[Initial build] modules\visual_script\register_types.cpp(51): note: due to following members:
Compiling drivers\vulkan\vulkan_context.cpp ...
modules\visual_script\register_types.cpp(51): note: 'void ScriptLanguage::reload_scripts(const Array &,bool)': is abstract
.\core/object/script_language.h(374): note: see declaration of 'ScriptLanguage::reload_scripts'
modules\visual_script\register_types.cpp(51): note: 'void ScriptLanguage::profiling_set_save_native_calls(bool)': is abstract
.\core/object/script_language.h(393): note: see declaration of 'ScriptLanguage::profiling_set_save_native_calls'
vulkan_context.cpp
scons: *** [modules\visual_script\register_types.windows.editor.x86_64.obj] Error 2
Compiler terminating.  Please wait........... Abort complete.
scons: *** [drivers\gles3\rasterizer_scene_gles3.windows.editor.x86_64.obj] Build interrupted.
scons: Build interrupted.
scons: building terminated because of errors.
scons: writing .sconsign file.
[Time elapsed: 00:00:41.552]

**Comment by Zylann** [comment]
I don't know about that one, I didn't use this API. But generally it's all changes done in Godot 4.3 that devs of this module have to figure out.
In the meantime you could try compiling with Godot 4.2 instead of latest master branch.

**Comment by ghost** [comment]
Ok I'll try

**Comment by ghost** [comment]
It took a bit of time but it works just fine thank you sooo much !
